### ISSUE TITLE
[Request] Android (Termux) support

### ISSUE THREAD

**Issue by NTBBloodbath** [orf/gping#102]
gping could be used within Termux on Android, but currently doesn't have support to be used on Android. Could compatibility be provided?

**Comment by orf** [comment]
Can you run “ping google.com” and “ping —version” on your android device and put the output here?

**Comment by NTBBloodbath** [comment]
> Result of `ping google.com`:

```
PING google.com (172.217.173.46) 56(84) bytes of data.
64 bytes from bog02s12-in-f14.1e100.net (172.217.173.46): icmp_seq=1 ttl=110 time=106 ms
64 bytes from bog02s12-in-f14.1e100.net (172.217.173.46): icmp_seq=2 ttl=110 time=142 ms
64 bytes from bog02s12-in-f14.1e100.net (172.217.173.46): icmp_seq=3 ttl=110 time=244 ms
64 bytes from bog02s12-in-f14.1e100.net (172.217.173.46): icmp_seq=4 ttl=110 time=120 ms
64 bytes from bog02s12-in-f14.1e100.net (172.217.173.46): icmp_seq=5 ttl=110 time=122 ms
^C64 bytes from 172.217.173.46: icmp_seq=6 ttl=110 time=246 ms

--- google.com ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5018ms
rtt min/avg/max/mdev = 106.252/163.821/246.851/58.823 ms
```

Result of `ping --version`:
```
ping: invalid option -- -
```

**Comment by orf** [comment]
Thank you, I think I can add support for this. Can you run "ping --help"?

I'm trying to see which flags are supported with ping on Android.

**Comment by NTBBloodbath** [comment]
> Result of `ping --help`:
```
ping: invalid option -- -
Usage: ping [-aAbBdDfhLnOqrRUvV] [-c count] [-i interval] [-I interface]
            [-m mark] [-M pmtudisc_option] [-l preload] [-p pattern] [-Q tos]
            [-s packetsize] [-S sndbuf] [-t ttl] [-T timestamp_option]
            [-w deadline] [-W timeout] [hop1 ...] destination
```

**Comment by orf** [comment]
Android should now be supported. No idea how to publish pre-built binaries for this platform, any advice would be awesome.

**Comment by NTBBloodbath** [comment]
> No idea how to publish pre-built binaries for this platform, any advice would be awesome.

I think you should only cross compile for the target platform (`arm-linux-androidaebi`) and it should work fine (I don't know how to compile binaries for Android x86 / x64 but the vast majority of Android devices are ARM).

I don't think it is necessary to make a native library call (Android NDK a `.so` file) from the code, so you shouldn't need any of that.

Ps: I would also just take my comment for reference, I have never compiled binaries or used Rust. I have only read some forums and posts about it.

**Comment by orf** [comment]
Alright, lets see! I've added `armv7-linux-androideabi` and `armv7-unknown-linux-gnueabihf` to the build process. I'm going to push a new release in a moment, so these should appear under the github release 🤞

**Comment by NTBBloodbath** [comment]
Nice to read that, I hope everything goes well!

Could you build for arm64 / aarch64 if it's not a bother? So I could test it (since at least I don't have armv6 or armv7) and so I let you know if it works well 🙂

**Comment by orf** [comment]
Sure, I've added `aarch64-linux-android` as a target now. Should be out in the next release

**Comment by orf** [comment]
Feel free to test! https://github.com/orf/gping/releases/tag/v1.0.1-post2

**Comment by NTBBloodbath** [comment]
Thank you very much, working like a charm on my android device!

![Running gping on Termux with aarch64](https://iili.io/FwC2cv.png)
