### ISSUE TITLE
[BUG] receiving on a closed channel

### ISSUE THREAD

**Issue by icefed** [orf/gping#104]
gping a Unknown host like "www.asdfasdgfasdg.com", get a "receiving on a closed channel" error after press "CTRL+C".

OS: Macos 10.15.5 (19F101) Intel CPU
gping Version: v0.1.7

**Comment by tzyluen** [comment]
I submitted a PR #108 to fix the issue. You may pull from my branch and help to test. I hope the owner will merge this fix on next release.
