### ISSUE TITLE
Suggestion: inline mode

### ISSUE THREAD

**Issue by pmarks-net** [orf/gping#107]
Instead of full screen, it'd be awesome if gping could occupy like 7 lines of text, and remain visible after `^C`.  Then people could scroll up and skim data from earlier runs.

I faked this screenshot:
![gping-inline-sketch](https://user-images.githubusercontent.com/4578188/100496637-62166180-310a-11eb-8cf5-9dc7e43078ba.png)

**Comment by orf** [comment]
Hey! This would be good, but I'm not sure how to implement this. I'll have a go now

**Comment by orf** [comment]
I've fixed this by not using the "alternative screen". Unfortunately this doesn't 100% work, as the new terminal line appears a bit above the bottom, but this is good enough for now?

<img width="1655" alt="Screenshot 2022-12-03 at 19 49 31" src="https://user-images.githubusercontent.com/1027207/205459223-42e4f693-65f4-4835-bca9-18c5e3b3eec9.png">

**Comment by pmarks-net** [comment]
This doesn't match the screenshot at all... it's still full-height, and the cursor appears in a random location after Ctrl-C.

If it were my code, I would either figure out how to do it correctly, or leave it alone.

**Comment by orf** [comment]
I agree, but I'm not sure if it's my terminal setup that's causing this or if it's a bug. 

I'll fix it before the release, but if you want to give it a try that would be helpful.

**Comment by pmarks-net** [comment]
I already tried it (via `cargo run`) before my previous comment. There are an infinite number of ways to write incorrect code, so I'm not sure why you'd expect it to work for me if it doesn't work for you.

**Comment by orf** [comment]
There are infinite ways to write incorrect code, but there are far fewer combinations of os, terminal emulator and shell, which presumably can influence this behaviour.

Narrowing that down to "it works for you, but not for me" is an obviously valuable exercise that I would assume wouldn't need to be spelled out.

Regardless, thanks for trying it 👍
