### ISSUE TITLE
Multi-Line string and Annotations

### ISSUE THREAD

**Issue by SuburbanFilth** [orf/gping#12]
1. So I fokred the repo and tried to run it on my OS X Yosemite but because of all the annotations it wont work. Python 2 doesnt support them. 

2. Is there a way to create perhaps another folder inside the master for python 2, if yes ill try to work on it.

**Comment by orf** [comment]
Thanks for MR #13, does this make it work on OS X with py2?

**Comment by SuburbanFilth** [comment]
I am at work atm but tonight ill try to remove all the annotations and ill let you know
