### ISSUE TITLE
Is gping not updating in homebrew?

### ISSUE THREAD

**Issue by chicks-net** [orf/gping#121]
https://formulae.brew.sh/formula/gping#default shows that the version is 1.2.0, but after I do

```
brew update
brew upgrade gping
```

it looked like it upgraded to 0.1.7:

```
==> Upgrading 1 outdated package:
orf/brew/gping 0.1.6 -> 0.1.7
==> Upgrading orf/brew/gping 0.1.6 -> 0.1.7 
==> Downloading https://github.com/orf/gping/releases/download/v0.1.7/gping-Darwin-x86_
```

And shows me that it is running 0.1.8:

```
$ gping -help
gping 0.1.8-alpha.0
Ping, but with a graph.
```

Are the updates to homebrew working or is my ancient MacOS (10.13) breaking this in some hidden fashion?

**Comment by orf** [comment]
You're using my old homebrew tap. Try "brew untap orf/brew", then "brew uninstall gping" and try again

**Comment by chicks-net** [comment]
That seems to have fixed it.  Thank you so much.  😃 

```
$ gping -help
gping 1.2.0
```
