### ISSUE TITLE
Option to customize the char used for drawing the graph

### ISSUE THREAD

**Issue by yermulnik** [orf/gping#122]
I'm using non-default non-system font for the terminal app on Linux Mint with `mlterm` and am wondering whether this output is something expected or the font is missing the drawing char?
![image](https://user-images.githubusercontent.com/1274789/101538143-55fd9000-39a5-11eb-978a-75eb990368d2.png)
Looks a bit weird to be fair =(
Is there an option to customize the char used to draw the graph?

**Comment by orf** [comment]
Closed now that we have `--simple-graphics`
