### ISSUE TITLE
Graphs are not displayed on Win7

### ISSUE THREAD

**Issue by Fixer-007** [orf/gping#123]
version 1.2.0, win7 sp1

![зображення](https://user-images.githubusercontent.com/16494741/101657347-72083c80-3a4c-11eb-90ed-c1871b3bad52.png)

**Comment by k79e** [comment]
Still same

**Comment by orf** [comment]
Run with `--simple-graphics`, or use a better terminal.

**Comment by Fixer-007** [comment]
--simple-graphics just makes it unresponsive and beeping.
