### ISSUE TITLE
0ms ping reported

### ISSUE THREAD

**Issue by ztNFny** [orf/gping#127]
For some sites gping is oscilating between 0ms and the normal ping time.

ping cp100.sp-server.net -> min 11, max 14
gping cp100.sp-server.net -> min 0, max 14

It seems that every second ping is recorded as 0ms

![image](https://user-images.githubusercontent.com/1258173/102888042-475cb180-4458-11eb-9876-046308e8bad3.png)

**Comment by orf** [comment]
Can you give your OS, what version of gping you are running and some lines of output from pinging that host?

**Comment by ztNFny** [comment]
Operating System: Fedora 33 (KDE Plasma)
       CPE OS Name: cpe:/o:fedoraproject:fedora:33
            Kernel: Linux 5.9.14-200.fc33.x86_64

gping 1.2.0

ping cp100.sp-server.net
PING cp100.sp-server.net (195.30.85.100) 56(84) bytes of data.
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=1 ttl=56 time=12.9 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=2 ttl=56 time=12.9 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=4 ttl=56 time=12.3 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=5 ttl=56 time=12.7 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=6 ttl=56 time=12.7 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=7 ttl=56 time=19.0 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=8 ttl=56 time=12.9 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=9 ttl=56 time=12.9 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=10 ttl=56 time=12.6 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=11 ttl=56 time=12.1 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=12 ttl=56 time=11.9 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=13 ttl=56 time=12.4 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=14 ttl=56 time=12.2 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=15 ttl=56 time=12.0 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=16 ttl=56 time=12.2 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=17 ttl=56 time=12.3 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=21 ttl=56 time=12.6 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=22 ttl=56 time=12.7 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=23 ttl=56 time=12.2 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=24 ttl=56 time=12.7 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=25 ttl=56 time=12.2 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=26 ttl=56 time=12.7 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=27 ttl=56 time=12.0 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=28 ttl=56 time=11.7 ms
64 bytes from cp100.sp-server.net (195.30.85.100): icmp_seq=29 ttl=56 time=11.9 ms

**Comment by barrowsys** [comment]
having the same issue on fedora 32 when my connection is very unstable, it seems to coincide with the ping timing out? it might be better to display timeouts as 4 seconds (the default for linux ping?)
![image](https://user-images.githubusercontent.com/41446523/108600255-30591380-7364-11eb-9272-120992d15759.png)
![image](https://user-images.githubusercontent.com/41446523/108600263-3b13a880-7364-11eb-8859-514df490f54f.png)

**Comment by adaasch** [comment]
+1
