### ISSUE TITLE
gping not work for proxy

### ISSUE THREAD

**Issue by daniel2643** [orf/gping#128]
I set a proxy for some websites such as google and facebook, gping not respond with any message. The same issue with ping:

PING www.google.com (154.92.16.97): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
Request timeout for icmp_seq 7
Request timeout for icmp_seq 8
Request timeout for icmp_seq 9
Request timeout for icmp_seq 10
Request timeout for icmp_seq 11
Request timeout for icmp_seq 12
Request timeout for icmp_seq 13

**Comment by barrowsys** [comment]
HTTP and SOCKS proxies don't handle pings,, maybe could add support for sending http requests instead of icmp packets? see also https://www.vanheusden.com/httping/

**Comment by orf** [comment]
We support arbitrary commands through the `cmd` flag. This can be used to profile HTTP endpoints (as well as any other).
