### ISSUE TITLE
[Feature request] Display jitter

### ISSUE THREAD

**Issue by MatiasFernandez** [orf/gping#132]
I love this tool, it's simple and effective. I would love to see a bit more information that is not present today, for example, jitter.

It could be helpful to see min, max, and p95. But at least showing p95 would be great.

Thanks!

**Comment by niutech** [comment]
Gping now shows min, max and p95, but not jitter - measured as the difference between samples divided by the number of samples minus 1.

**Comment by niutech** [comment]
I made a PR with jitter calculated like [here](https://www.pingman.com/kb/article/what-is-jitter-57.html).
