### ISSUE TITLE
[Feature Request] Ping range by mask 

### ISSUE THREAD

**Issue by crlsgms** [orf/gping#136]
instead of manually adding each ip, the possibility to choose an entire range, such as 10.0.0.1/26 

Maybe another parsing in  fn get_host_ipaddr ?

**Comment by niutech** [comment]
You can just run `gping 10.0.0.{1..63}` in bash.

**Comment by orf** [comment]
I looked at adding this, but I'm not sure it's simple to add. I think adding anything other than a /26 would not work, as it would launch a ridiculous number of ping processes and the bash command above is fine.
