### ISSUE TITLE
Octal and hexadecimal ipv4 address parsing

### ISSUE THREAD

**Issue by arnabanimesh** [orf/gping#144]
Windows ping command use [`inet_addr`](https://datatracker.ietf.org/doc/html/rfc6943#section-3.1.1) standard which recognizes octal and hexadecimal ipv4 addresses
 e.g. 0xC00002EB => 192.0.2.235; 011.012.013.014 => 9.10.11.12

It would be great if this app could maintain parity with the functionality of traditional ping apps.

[This gist provides a good reference](https://gist.github.com/LuoZijun/df2d57ab6f5217a4bd18)

**Comment by orf** [comment]
I'm going to close this because Rust doesn't support it, and according to this PR (https://github.com/rust-lang/rust/pull/83652) it says:

> This confusion can lead to many security vulnerabilities. Therefore, in
> IETF RFC 6943, it suggests to disallow octal/hexadecimal format in Ipv4
> string all together.

Which is also noted here: https://doc.rust-lang.org/std/net/struct.Ipv4Addr.html#textual-representation
