### ISSUE TITLE
Empty screen without host

### ISSUE THREAD

**Issue by ryuheechul** [orf/gping#145]
How to reproduce: simply type `gping`

Now empty screen is being shown but still possible to exit with `q`. 

When first time this happened, I wasn't sure if it was loading for something or not.

Maybe it's good to expliclity fail and print help (as if user typed `gping --help`) instead?

The version of `gping` installed on my machine is `1.2.1` on M1, macOS.

**Comment by orf** [comment]
Hey, this shouldn't be an issue with the latest release.
