### ISSUE TITLE
adjust ping frequency

### ISSUE THREAD

**Issue by hungrysnake** [orf/gping#149]
Hi gping,

is it possible to have an option to adjust/reduce the ping frequency like the ordinary ping tool. e.g 1 ping/s?
ths reason is the default/current ping is about 5 ping/s (0.2s interval), for 10 hosts, i send sending 50 icmp/s, it may trigger some alert in the firewall.

pining 4 host at the same time.
![image](https://user-images.githubusercontent.com/42885440/136908476-658749f2-bf07-4804-829d-c4d557a084c8.png)

**Comment by barrowsys** [comment]
yeah good point,, the -n option only seems to affect command interval, not ping interval
