### ISSUE TITLE
Pinging by domain broken as of latest release 1.3.0

### ISSUE THREAD

**Issue by ryannathans** [orf/gping#167]
gping 1.3.0
commit_hash: 01de30f8

Pop OS 20.04 LTS

`gping google.com cloudflare.com -4`

![image](https://user-images.githubusercontent.com/1307375/155822950-8f82632c-3d90-406c-a75f-b2d6ea1fa9d4.png)

`gping 172.217.167.110 104.16.133.22`

![image](https://user-images.githubusercontent.com/1307375/155822999-0009728d-fc55-4c36-9013-735c56388a34.png)

**Comment by orf** [comment]
Unfortunately I'm unable to reproduce. I've added more context to the resolution error here: https://github.com/orf/gping/commit/4050fa5e8f2a4f167b6a704a06b86b6cdc57c2af

I'll push a release with that shortly.
