### ISSUE TITLE
Consider adding GitHub topics?

### ISSUE THREAD

**Issue by chmac** [orf/gping#168]
Just discovered gping, firstly, thanks for releasing it, looks awesome.

I wonder if you'd consider adding topics to the repo? I found the repo via searching brew formulae for ping, but I couldn't find it via the topic search on github. Would maybe help others find the package to add them.

**Comment by orf** [comment]
Thanks for the idea! I've added a few just now, let me know if you have any specific suggestions for other ones to add?

**Comment by chmac** [comment]
@orf Awesome, this is now the number 2 project for the ping topic!

Maybe `graph`, `network-monitoring` or `shell`? I copied from prettyping!
