### ISSUE TITLE
Could not find debian:buster-slim mirror

### ISSUE THREAD

**Issue by mingtianshi** [orf/gping#181]
[Dockerfile](https://github.com/orf/gping/blob/master/Dockerfile) website link.

**Comment by orf** [comment]
https://hub.docker.com/layers/debian/library/debian/buster-slim/images/sha256-dfa8be0c158e556532b023717650ee2ab52ed2b1b792a5810db138708101548a?context=explore It exists?

please can you explain your issue some more
