### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by vlakam** [orf/gping#20]
http://i.imgur.com/JhWc7oy.png
pip3 says that installation is successfull, but i can't use gping.

**Comment by orf** [comment]
Strange, can you give the output of `whereis gping`?

**Comment by ATrigger** [comment]
kamenev@SamsungN150:~$ whereis gping
gping:

**Comment by orf** [comment]
Hmm, I think this is something to do with your environment rather than the project. Please try installing the latest `0.0.11` release, but I just tried on my Ubuntu box with both 2.7 and 3.4 and it worked fine.

**Comment by ATrigger** [comment]
Tried uninstall and then re-install. No effect.
Running xubuntu 15.04 x86

**Comment by ATrigger** [comment]
Migrated to a fresh copy of xubuntu 15.04 amd64.
Problem persists

**Comment by orf** [comment]
Hmm this is really strange, I will try and find some time tomorrow to look into this. Can you make a virtualenv (`python3 -mvenv directory && source directory/bin/activate`) and try and install it there? It might be a configuration option within xubuntu that stops packages installed in the global Python interpreter from making bin files?

**Comment by karolmie1** [comment]
@ATrigger Sorry for asking you such an basic question, but: 
1. Please locate where is gping file on your computer (if you've installed is as a --user then it would be under .local/bin)
2. Check if this folder is added to your path: echo $PATH

If it is not, then you just have to set it in your .bashrc, and source it: source ~/.bashrc
