### ISSUE TITLE
Any good recommendations of colors for an older Windows 10 and earlier PowerShell / cmd usage that is easy to differentiate?

### ISSUE THREAD

**Issue by ylluminate** [orf/gping#203]
I've been playing around a bit with color theme options for use cases when you have 6 to 10 IP addresses that need to be monitored and it is very difficult to differentiate the different IP addresses when using Windows 10 and earlier that are bound to the traditional Windows terminal (eg, cmd.exe and PowerShell pre the new Windows Terminal app).

Has anyone come up with a definition of 10 or more colors that are relatively easy to differentiate in these scenarios where there is very little or poor control over the color selection and background option (generally working with black or very dark blue)?

**Comment by orf** [comment]
Hey, I’m not sure this is an issue with gping. Win10 and earlier and harder to support because yes, the console sucks.

If you can suggest a colour palette that works well i would re-open this and we can potentially make the default colour scheme use that.

until then I’d recommend not using the default terminal - there are others out there that work better, even if you don’t use power shell.

**Comment by ylluminate** [comment]
You may be right here in terms of using a different terminal like ConEmu. I was hoping to get as close to vanilla as possible since I maintain a number of systems that need to be configured and I didn't really want to do much modification beyond simply using `scoop` to install `gping`... but it's looking like the easiest/cleanest path may be to simply use ConEmu so that it supports superior font options (such as facilitating the braille dots default that seems to present better than the other bulky `-s` single dot option).

Hmmm.  Furthermore, however, the colors are still not optimal and it seems that better support / delineation is needed somehow.

For example, it's helpful to differentiate categories of different subnets, perhaps, by color groups. So, for example, LAN IP addresses might be grey-neutral colors while certain and various WAN addresses (remote ISP gateways, DNS servers, etc.) could be grouped in brighter colors with red or yellow shades being the most attention worthy. At least this is  what I'm thinking about right now...

**Comment by AaronCompNetSys** [comment]
Here is the list of colors: 'black', 'red', 'green', 'yellow', 'blue', 'magenta',
'cyan', 'gray', 'dark-gray', 'light-red', 'light-green', 'light-yellow', 
'light-blue', 'light-magenta', 'light-cyan', and 'white' 

found via https://github.com/orf/gping/blob/08633c8528018bf37c3a7f144ab1a1cbf38288cc/gping/src/main.rs#L120

For powershell, I chose light-red,white,green

Not all of them work....
