### ISSUE TITLE
Suggestion: Interface selection

### ISSUE THREAD

**Issue by Superminaren** [orf/gping#206]
It would be awesome to be able to select interface to use for the sake of debugging paths where ping-related issues arise come from.

**Comment by orf** [comment]
I like this idea. Would you want to be able to specify this per domain? I.e be able to ping google twice, one via each interface?

**Comment by Superminaren** [comment]
That would come in handy, for example in interface comparisons for sure.
However the primary issue today is one of trying to debug latency on a WiFi
network and having the ping tool use eth0 sporadically causing inconclusive
measurements.
