### ISSUE TITLE
Could not detect ping command type

### ISSUE THREAD

**Issue by presianbg** [orf/gping#216]
Hi,

I'm having the following error when trying to use the tool on `Solus` linux:

```
Error: Could not detect ping command type

Caused by:
    Could not detect ping. Stderr: []
    Stdout: ["ping (GNU inetutils) 2.2", "Copyright (C) 2021 Free Software Foundation, Inc."]
```

```
./gping --version                                                                                                                                                                                  
gping 1.4.0
commit_hash: d8d38bc6
build_time: 2022-09-19 20:18:53 +00:00
build_env: rustc 1.63.0 (4b91a6ea7 2022-08-08),
```
```
ping (GNU inetutils) 2.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Sergey Poznyakoff.
```

Any ideas what might be the problem of this ?

Cheers,
PY

**Comment by presianbg** [comment]
Looks like the `ping` package from https://github.com/iputils/iputils is needed. 
Closing.

**Comment by orf** [comment]
Hey! This is still an issue, I'm going to reopen this now and add support for iptuils ping

**Comment by presianbg** [comment]
> Hey! This is still an issue, I'm going to reopen this now and add support for iptuils ping

Nice, but `ping` from `inetutils` is the one which should be added, not `iputils` :)

**Comment by orf** [comment]
Unfortunately `inetutils` doesn't seem to support outputting `timeout` messages. It only outputs messages when pings are returned, and also you need to use a different binary name for ipv6?

I've made a change in b91c59c7bb2331103349a5edc1589fb0fef64846 to throw an error when inetutils is used, telling people to use iptools instead.

Sorry!
