### ISSUE TITLE
FR: Show last ping value

### ISSUE THREAD

**Issue by Zahrun** [orf/gping#223]
I would like to see the last ping value as part of the values which are shown as text. Under some conditions, it might be difficult to read the graph.
![image](https://user-images.githubusercontent.com/10415894/198013903-9c674965-37ed-4df9-9ae1-bdf9131e43e9.png)

**Comment by japonka** [comment]
Иди на хуй!

Ср, 26 окт. 2022 г. в 14:24, Aroun ***@***.***>:

**Comment by orf** [comment]
Haha, good point. Seems like a good idea! Contributions welcome, this should be a fairly easy change to make

**Comment by Zahrun** [comment]
Nice, thank you!
