### ISSUE TITLE
Is it installable on Debian bullseye?

### ISSUE THREAD

**Issue by EVOTk** [orf/gping#225]
Hello,
I'm sorry if my question seems silly but, in the installation doc the repository is "buster", does that mean that qping can't be installed on "bullseye"?

![image](https://user-images.githubusercontent.com/45015615/201781588-758d6350-d2fc-40af-9504-7574497acea2.png)

Thx

**Comment by japonka** [comment]
hi why are you asking me this?

Вт, 15 нояб. 2022 г. в 01:30, EVOTk ***@***.***>:

**Comment by werdahias** [comment]
It can. This only means that the repo works from buster upwards afaik. I'm working on an official debian package, so it might make it into the bookworm release.

**Comment by orf** [comment]
Awesome, thanks for clarifying @werdahias. Let me know if I can help with anything related to an official debian package.

**Comment by werdahias** [comment]
@orf I'm only missing pinger and shadow-rs for a debian package

**Comment by azlux** [comment]
You can switch buster to bullseye, or even "stable" to have last update, It's the same.
