### ISSUE TITLE
Use own mean() function.

### ISSUE THREAD

**Issue by SanketDG** [orf/gping#23]
Instead of using `statistics.mean` that breaks compatibility between python2 and python3, we can simply implement a `mean(data)` function that returns `sum(data)/len(data)`

I can send you a PR if you are okay with this.

**Comment by orf** [comment]
Good idea, thanks! Fixed in 5b55fa7

**Comment by SanketDG** [comment]
@orf Looks like this now works perfectly in 2.7, so the information about 2.7 can be removed.

**Comment by orf** [comment]
Done in  f9791de, thanks :)
