### ISSUE TITLE
libc version

### ISSUE THREAD

**Issue by azlux** [orf/gping#233]
Hi,
On your last version you used the libc lib version 2.33/2.32/2.64

```
root@L-20200907-03:~# gping
gping: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by gping)
gping: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by gping)
gping: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by gping) 
```
But current libc on debian stable (bullseye) is 2.31

```
root@L-20200907-03:~# dpkg -l | grep libc6
ii  libc6:amd64                   2.31-13+deb11u5                amd64        GNU C Library: Shared libraries
```

Is the libc version you request mandatory ?

**Comment by orf** [comment]
Hey @azlux, are you talking about the prebuilt binaries?

**Comment by azlux** [comment]
Yes, 
My repo use them directly (L15 of https://packages.azlux.fr/scripts/gping.txt):
> dist['amd64']='-Linux-x86_64.tar.gz'
The autoupdate is looking for this zip file.
