### ISSUE TITLE
Color preferences are broken some versions ago

### ISSUE THREAD

**Issue by delphersf** [orf/gping#239]
Hello! Thank you so much for so useful program!

Of about several weeks (some versions) ago I've got some **bugs with broken color preferences (sequences)**.

I used command like:
`gping -4 --vertical-margin 0 --horizontal-margin 0 --color '#FF0000' '#FF00FF' '#8800ff' '#87CEFA' '#00FFFF' '#00FF00' '#FFFF00' '#FF4500' '#A9A9A9' '#FFFFFF' --watch-interval 5 --buffer 1800  8.8.8.8 1.1.1.1 google.com`

or like this:
`gping -4 --vertical-margin 0 --horizontal-margin 0 --color red green --watch-interval 5 --buffer 1800  8.8.8.8 1.1.1.1 google.com`

And now I've got the error like _(links to the 2nd color at command)_:
```
Error: failed to lookup address information: Name or service not known
Caused by:
    Could not resolve hostname #FF00FF
```
Hope you'll fix this some day :)
God bless you!

**Comment by orf** [comment]
Hi! you need to pass these as comma separated values. I'm not sure how it worked before 🤔

**Comment by delphersf** [comment]
> Hi! you need to pass these as comma separated values. I'm not sure how it worked before thinking

I just tried using commas, and there is the **same result** :(

**Comment by orf** [comment]
you're quite right @delphersf - I messed up the commit. I've actually fixed it and will push out a release soon
