### ISSUE TITLE
what is t/o?

### ISSUE THREAD

**Issue by chanansh** [orf/gping#247]
![image](https://user-images.githubusercontent.com/5981644/209441038-89a6e0ec-4f7a-4563-a4bd-3c6eafb3711d.png)

**Comment by orf** [comment]
Timeout

**Comment by NonlinearFruit** [comment]
I had the same question. Is there somewhere with more detail/explanation of the TUI?

**Comment by Zahrun** [comment]
Same here, I had a doubt. Maybe it could be expressed in the help message or in the readme
