### ISSUE TITLE
Latest release workflow failed

### ISSUE THREAD

**Issue by suzuki-shunsuke** [orf/gping#260]
https://github.com/orf/gping/actions/runs/4027601483/jobs/6923522249

```
Run softprops/action-gh-release@v1
⬆️ Uploading gping-armv7-unknown-linux-gnueabihf.tar.gz...
⬆️ Uploading gping.1...
Error: Failed to upload release asset gping.1. received status code 422
Validation Failed
[{"resource":"ReleaseAsset","code":"already_exists","field":"name"}]
```

Due to this failure, [Cross-build (x86_64-unknown-linux-musl)](https://github.com/orf/gping/actions/runs/4027601483/jobs/6923523177#step:6:89) was cancelled so gping-x86_64-unknown-linux-musl.tar.gz wasn't released in [gping-v1.8.0](https://github.com/orf/gping/releases/tag/gping-v1.8.0).

**Comment by orf** [comment]
Nuts! Thanks for this. I’ve re-triggered it here: https://github.com/orf/gping/actions/runs/4027601483

**Comment by suzuki-shunsuke** [comment]
Thanks. [gping-x86_64-unknown-linux-musl.tar.gz](https://github.com/orf/gping/releases/download/gping-v1.8.0/gping-x86_64-unknown-linux-musl.tar.gz) was released successfully.
[Cross-build (armv7-unknown-linux-gnueabihf)](https://github.com/orf/gping/actions/runs/4027601483/jobs/6927350769#step:4:10) was cancelled, but [gping-armv7-unknown-linux-gnueabihf.tar.gz](https://github.com/orf/gping/releases/download/gping-v1.8.0/gping-armv7-unknown-linux-gnueabihf.tar.gz) was already released so I guess there is no problem.

Thanks again.
