### ISSUE TITLE
Please license this so I can distirbute it in Gentoo

### ISSUE THREAD

**Issue by blueness** [orf/gping#27]
I'm a Gentoo developer and would like to start distributing this Gentoo.  However, it is not yet licensed.  Can I recommend GPL-2.

**Comment by orf** [comment]
Hey there,
Absolutely, I will add the licence tonight. There are a few encoding
related issues I would like to sort out before this is ready for
distribution, but getting it included with Gentoo sounds very exciting!

**Comment by orf** [comment]
Added in e7ba1f6. I went with the GPL-2, but it was a toss up between that and MIT. Is there anything else I need to add to allow distribution?

One of the major issues with *nix and this tool is that the `ping` command doesn't report timeouts (and there doesn't appear to be an option to display them). This makes the graph freeze when timeouts occur, I don't suppose there is an option for this in the version of `ping` that Gentoo ships with?

**Comment by blueness** [comment]
i'm adding it first to my overlay and then to the main tree as "experimental" so that i can work on it in gentoo and contribute upstream to you.  i can' t do either that without some license that says i'm allowed to publicly distribute it.  gentoo is a from source distro and we have magic that pulls directly from your repo, builds and installs into the filesystem, making a full circle in the dev cycle.  i'll be able to work on all aspects of it end-to-end.  so will other users that might get interested.

if ping doesn't provide a proper timeout, set a sigalarm before any invocation of ping and a handler that cleans up the hanging child, then maybe draw a funky colored bar to indicate a timeout.

**Comment by blueness** [comment]
this issue is done, you've got a license in there.  closing.
