### ISSUE TITLE
How do I build gping?

### ISSUE THREAD

**Issue by garyemiller** [orf/gping#287]
The Gentoo version is 1.5.1, so I want to build from source.  But I see no Makefile.

How do I build this thing?

**Comment by orf** [comment]
https://letmegooglethat.com/?q=how+do+i+build+a+rust+project%3F

Or like any other basic searching of the CI scripts, or just really anything else. Is it *honestly* quicker for you to open a GitHub issue and ask me to respond?

**Comment by garyemiller** [comment]
I have never built a rust program before.  I did not even realize gping was built in rust, and from the README, I thought "Cargo" was a Distribution, it is in the middle of distribution instructions, so did not realize it was a build system.


I figure that when one person asks a question that 9 others had the same question, so it is best to update the doc.  Now that I see how to build it, I would suggest the readme does what other readmes do, and have a separate section on "building from source".

I'm not gonna google for an hour to learn yet another language and yet another build system, that I'll never need to know again, just to type one line to build something.  I know I'm not alone in this, and the simple doc fix mentioned above will solve the problem for those that build from source.

**Comment by orf** [comment]
It’s ok, and I’m sorry for my flippant response. As the number of projects I have grows so do the number of issues, and sometimes if you wake up on the wrong side of bed this makes for problematic responses.

Your point about adding it to the readme is valid, I’ll add it to my to-do list (or accept any PRs with instructions).
