### ISSUE TITLE
Doesn't work on linux mint

### ISSUE THREAD

**Issue by avacore1337** [orf/gping#3]
On Linux Mint I get the following error:

gping google.com

Traceback (most recent call last):
  File "/usr/local/bin/gping", line 7, in <module>
    from gping.pinger import run
  File "/usr/local/lib/python3.4/dist-packages/gping/pinger.py", line 11, in <module>
    from colorama.ansitowin32 import winterm
ImportError: cannot import name 'winterm'

Can you give any hints on how this could be solved?

**Comment by orf** [comment]
I pushed a fix for that last night, could you try it again and let me know if it works?

**Comment by avacore1337** [comment]
It works now.

Thank you!
