### ISSUE TITLE
x86_64 musl build no longer provided?

### ISSUE THREAD

**Issue by pataquets** [orf/gping#300]
Latest was 1.8.0. Later releases do not provide it, so I'm behind on Ubuntu Bionic.

**Comment by orf** [comment]
There was an issue with the release process (https://github.com/orf/gping/actions/runs/5045284757/jobs/9049363391)

I re-ran the job and the releases are now present: https://github.com/orf/gping/releases/tag/gping-v1.11.0. I'm working on fixing this properly.

**Comment by pataquets** [comment]
@orf: Release 1.12.0 assets are missing manpage file (not in the musl tar, neither)
