### ISSUE TITLE
Update gping snap

### ISSUE THREAD

**Issue by manikandancode** [orf/gping#314]
https://snapcraft.io/gping

OS: Ubuntu 23.04 Wayland

![image](https://github.com/orf/gping/assets/46480489/fbee8512-df25-44f6-b2ea-10fe7891abab)

**Comment by orf** [comment]
Hey, snap is not a supported installation method. Please check the project readme for the correct ways to install gping

**Comment by boukendesho** [comment]
@orf Sorry for reply here. I like gping and appreciate the project. I have some experience on packing snap and want to help to maintain the snap version gping. Is it possible? Thank you !
