### ISSUE TITLE
Unable to install gping using Ubuntu/Debian (Azlux's repo)

### ISSUE THREAD

**Issue by manikandancode** [orf/gping#315]
OS: Ubuntu 23:04

![image](https://github.com/orf/gping/assets/46480489/1f92da8c-28f6-4a22-88f2-282ce85e004b)

**Comment by orf** [comment]
I’m happy to support users with gping questions, but I am not really happy with people who open multiple issues in quick succession and do absolutely nothing to investigate the issue themselves.

try doing that first, and reply to this issue with any problems that may arise after the slightest bit of self investigation.
