### ISSUE TITLE
Use curses module?

### ISSUE THREAD

**Issue by webmaven** [orf/gping#32]
Python has a [curses module](https://docs.python.org/2/library/curses.html) in the standard library that might simplify the code a bit and make the graph a bit prettier.

**Comment by orf** [comment]
So I wanted to make this as cross platform as possible, curses would be cool but it's obviously *nix only. I could make a *nix specific graph function I guess, but then we are maintaining two separate codepaths.

Plus I think the graphs are pretty, could maybe use a character other than `#`?

**Comment by webmaven** [comment]
Yeah, using the block character would give you solid bars: █

**Comment by lilydjwg** [comment]
Hi, I find your graphs flicker when updating, maybe you are redrawing the whole screen every time?
If you use ncurses, it should figure out which part to update automatically, or you can do this yourself.

**Comment by webmaven** [comment]
@orf, any chance of changing the character from ```#``` to ```█```? It really would look much better.

**Comment by orf** [comment]
@webmaven Sure thing, I'm going to experiment tonight and hopefully fix the flickering @lilydjwg

**Comment by orf** [comment]
<img width="585" alt="screenshot at feb 20 21-50-59" src="https://cloud.githubusercontent.com/assets/1027207/13199385/1f0e754a-d81c-11e5-90f0-24b6cfc0a5ca.png">
So this is what it looks like with the unicode BLOCK element. To be honest I don't like it, the spaces between the blocks ruin it. Anyone know how to get rid of that?

**Comment by orf** [comment]
Meh, it appears to look better in Windows (and it does look a lot better than `#`). I've pushed a new release :)
