### ISSUE TITLE
gping -help or gping -h is blocking

### ISSUE THREAD

**Issue by Naereen** [orf/gping#33]
Hi. Nice script :+1: !

But, asking for help blocks completely the script:
```bash
$ gping -help
Usage: ping [-aAbBdDfhLnOqrRUvV] [-c count] [-i interval] [-I interface]
            [-m mark] [-M pmtudisc_option] [-l preload] [-p pattern] [-Q tos]
            [-s packetsize] [-S sndbuf] [-t ttl] [-T timestamp_option]
            [-w deadline] [-W timeout] [hop1 ...] destination

(nothing else, it stops here, blocked)
```

Then it consumes 100% of one core without doing anything:
![100_percent_gping_help](https://cloud.githubusercontent.com/assets/11994719/11212481/5d97e494-8d36-11e5-92b3-297f2cb51f57.png)

(it might be a Python2 / pip2 specific problem, I have not tried with pip3)

**Comment by orf** [comment]
Thanks for reporting! I'll fix this, it's just not realizing that ping has died. I'll fix this tonight and push a new release.

**Comment by Naereen** [comment]
Thanks :tophat:. No hurry though.

**Comment by Naereen** [comment]
Great, it works fine, thanks! 95ebfc22 did the job.

But I think you lost the support of Python 2.7:

```log
$ gping dord.horse
Traceback (most recent call last):
  File "/usr/local/bin/gping", line 9, in <module>
    load_entry_point('pinggraph==0.0.12', 'console_scripts', 'gping')()
  File "/usr/local/lib/python2.7/dist-packages/gping/pinger.py", line 304, in run
    _run()
  File "/usr/local/lib/python2.7/dist-packages/gping/pinger.py", line 330, in _run
    plotted = plot(width, height, buff, host)
  File "/usr/local/lib/python2.7/dist-packages/gping/pinger.py", line 172, in plot
    "█", column + 2, 2, 2 + bar_height, paint=_paint
  File "/usr/local/lib/python2.7/dist-packages/gping/pinger.py", line 73, in vertical_line
    self[column, y] = (next(data_iter), paint)
StopIteration
```

It might have something to do with the updated version of colorama?

The Python 3.4 version works perfectly fine on my laptop.

**Comment by orf** [comment]
Damn Python 2.7. I've pushed a fix, did that fix it for you?

**Comment by Naereen** [comment]
It seems.
I will try on other machines next week, but I guess it's fixed.

(I don't know if its intentional, but the gping script installed by pip3.4 and pip2.7 on my /usr/local/bin/ are very different, 3.4 installs a hand-written script and 2.7 an EASY_INSTALL one)
