### ISSUE TITLE
Division by zero error on <1ms ping connections

### ISSUE THREAD

**Issue by cameronoca** [orf/gping#34]
![screen shot 2016-05-21 at 3 51 17 pm](https://cloud.githubusercontent.com/assets/13686317/15451220/e6bfddcc-1f6b-11e6-924a-bece4ce19167.png)

**Comment by orf** [comment]
! Good catch, I'll deal with this later this week unless you can make a
patch? To be honest the whole scaling thing doesn't really work very well,
I might rip it out and re-do it.
