### ISSUE TITLE
Installation on Mac OS Sierra

### ISSUE THREAD

**Issue by calvaradobcm** [orf/gping#37]
Hi, i know this may be very basic, but would it be possible that you explain how to install gping on MacOS Sierra, i know the OS already have Python 2.6 Installed and I also downloaded and upgraded to 3.5. The "pip3 install pingggraph" works, but when I try to lauch it using "gping 8.8.8.8"  it says "-bash: gping: command not found"

Thanks in advance. 

Regards!

**Comment by orf** [comment]
Hey, no problem for asking :) can you try "sudo pip3 install..."?

I'll try it when I get home and see if it's broken.

**Comment by calvaradobcm** [comment]
@orf It worked! Thanks!
