### ISSUE TITLE
gping snap fails under strict confinement

### ISSUE THREAD

**Issue by popey** [orf/gping#41]
Thanks for making a snap of gping! It's pretty.

Unfortunately under strict confinement it fails. Looks like you need an extra plug and binary perhaps?

```
Traceback (most recent call last):
  File "/snap/gping/6/bin/gping", line 11, in <module>
    load_entry_point('pinggraph==1.0', 'console_scripts', 'gping')()
  File "/snap/gping/6/lib/python3.5/site-packages/gping/pinger.py", line 313, in run
    _run()
  File "/snap/gping/6/lib/python3.5/site-packages/gping/pinger.py", line 338, in _run
    for line in it(options):
  File "/snap/gping/6/lib/python3.5/site-packages/gping/pinger.py", line 251, in _inner
    ping = subprocess.Popen(args, stdout=subprocess.PIPE)
  File "/snap/gping/6/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/snap/gping/6/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
```

```
alan@hal:~$ snappy-debug.security scanlog
sysctl: permission denied on key 'kernel.printk_ratelimit'
= AppArmor =
Time: Aug  3 01:40:37
Log: apparmor="DENIED" operation="open" profile="snap.gping.gping" name="/proc/24006/mounts" pid=24006 comm="python3" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
File: /proc/24006/mounts (read)
Suggestions:
* adjust program to not access '@{PROC}/@{pid}/mounts'
* add one of 'mount-observe, network-control' to 'plugs'

= AppArmor =
Time: Aug  3 01:40:37
Log: apparmor="DENIED" operation="exec" profile="snap.gping.gping" name="/bin/ping" pid=24022 comm="python3" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0
File: /bin/ping (exec)
Suggestions:
* adjust snap to ship 'ping'
* adjust program to use relative paths if the snap already ships 'ping'
```

**Comment by orf** [comment]
There is a lesson here: Don't release software late at night, kids! Thanks for reporting thia though. Snaps look very interesting by the way, I'm planning to snapify all my current projects.

So how should a snap fix this? I don't really want to add a 'ping' executable to the repo, should I adjust my configuration to install whatever package ping comes in? Or perhaps it's already available at a relative 'bin/ping' path?

**Comment by popey** [comment]
You could add:-

```
stage-packages:
  - iputils-ping
```

Which would indeed include ping (and whatever else is in the iputils-ping package, which you could prune). However I tried this and it seems the ping executable has a sticky bit which breaks inside snap. I suggest asking the snap / snapcraft developers on their forum. If you start a thread there I can ping the relevant people to get a response.

http://forum.snapcraft.io/

**Comment by orf** [comment]
Thanks for the help! I've made a thread here: https://forum.snapcraft.io/t/executing-ping-within-a-snap/1540

**Comment by popey** [comment]
Tested the version you pushed, looks like you've got it working. Nice one!
