### ISSUE TITLE
Function additions and suggestions

### ISSUE THREAD

**Issue by angel20009123** [orf/gping#413]
![333333333333333333333](https://github.com/orf/gping/assets/68273012/1461986f-9783-4cc0-a64c-d7adf9c5518f)

Function additions and suggestions
1：You can manually define a delay to hierarchically differentiate multiple results in the graph
2：When a ping result is not successful, manually define a return value, such as connection failure or network unreachable. If all fail, the output result will be a red alarm, and the result can be customized

**Comment by orf** [comment]
Thanks for the suggestion, but I don’t have time to add this right now, and it would greatly complicate the project.
