### ISSUE TITLE
[question] Using pinger as a library directly

### ISSUE THREAD

**Issue by Sparkenstein** [orf/gping#428]
gping is good, but I was trying to use the underlying `pinger` lib directly, with my own custom UI. I believe I was able to make something work with

```toml
pinger = { git = "https://github.com/orf/gping", branch = "master", package = "pinger" }
```
In Cargo.toml. But my project fails building with outdated `anyhow` version:

```sh
error: failed to select a version for `anyhow`.
    ... required by package `pinger v1.1.0 (https://github.com/orf/gping?branch=master#91bf2923)`
    ... which satisfies git dependency `pinger` of package `app v2.0.0 (E:\Projects\app\src)`
versions that meet the requirements `^1.0.75` are: 1.0.79, 1.0.78, 1.0.77, 1.0.76, 1.0.75
```

Is there a possibility to upgrade anyway in gping? Or can you think of any other way I can use pinger directly? I believe the old repo is archived and not updated in a long time.

**Comment by orf** [comment]
Hey! I've added a [README](https://github.com/orf/gping/tree/master/pinger) and an [example](https://github.com/orf/gping/blob/master/pinger/examples/simple-ping.rs) - let me know if it's clear!

Not sure about your actual issue, but you can/should just install it from `crates.io` rather than git.
