### ISSUE TITLE
Interface Switch does not work in Windows

### ISSUE THREAD

**Issue by neocharles** [orf/gping#440]
It appears that regardless of what you provide with -i or --interface, windows ignores that and does not send out the traffic out of the specified interface.

I tested by putting in a fake interface name and it still sent out pings.  Verified in wireshark that no traffic was going out the interface I did specify during initial testing.

gping 1.16.1
commit_hash: a46bd72d
build_time: 2024-02-17 11:50:08 +00:00
build_env: rustc 1.76.0 (07dca489a 2024-02-04),stable-x86_64-pc-windows-msvc

**Comment by orf** [comment]
This isn't easy to fix, especially as the crate we are using (https://docs.rs/winping/) is pretty old and doesn't support it. For now I've disabled the interface flag on Windows so that this is less confusing.
