### ISSUE TITLE
About Gping Graph

### ISSUE THREAD

**Issue by DwijadasDey** [orf/gping#45]
Hi
    Installed gping, but does this Graph is ok in Ubuntu 16.04 ? 
https://asciinema.org/a/YvT0tiLjpICwiTnSUqbd2uYoo

**Comment by orf** [comment]
It doesn't look great, but your connection looks awesome :) Try running `gping reddit.com` for `gping example.com`, you should get some more interesting graphs.

Let me know if both of those commands output the same graph.
