### ISSUE TITLE
-4 is using ICMPv6

### ISSUE THREAD

**Issue by exmatrikulator** [orf/gping#450]
If you provide the '-4' flag the IPv4 address will be shown.
But if you look into the packages IPv6 package are send.

**Comment by orf** [comment]
Can you be more clear? What OS are you using, and what specific command are you running?

**Comment by exmatrikulator** [comment]
I'm using Manjaro.
- make sure you have a internet connection with IPv4 and IPv6 working.
- start `tcpdump -i <interface> -n 'icmp or icmp6'` in the background
- watch the difference between `gping google.com` and `gping google.com -4`

gping shows different IPs(4/6), but tcpdump shows only IPv6.

**Comment by orf** [comment]
Thank you for this information, it is really helpful. I’ll take a look. 

Could you also give me the version of ping you’re using? That should be all I need to fix this.

**Comment by exmatrikulator** [comment]
gping --version
```
gping 1.17.3
commit_hash: 
build_time: 2024-07-25 21:20:32 +00:00
build_env: rustc 1.79.0 (129f3b996 2024-06-10) (Arch Linux rust 1:1.79.0-3),
```

**Comment by orf** [comment]
Hey - this is fixed now, and will be released shortly. Thanks for the report!
