### ISSUE TITLE
[Feature request] "Tag" target hosts for better overview

### ISSUE THREAD

**Issue by jandahl** [orf/gping#458]
It would be handy if the IP information at the top of the bar could have arbitrary information, static or dynamic.

Static example:

```
1.2.3.4 (1.2.3.4) - Customer A
8.16.32.64 (8.16.32.64) - Customer B
```

Dynamic example (using `whois $ip | awk -F ': +' '/^[Nn]et[Nn]ame:/ {print $2}'` to get ISP information)

``` 
1.2.3.4 (1.2.3.4) - Debogon-prefix
8.16.32.64 (8.16.32.64) - LVLT-ORG-8-8
```

**Comment by orf** [comment]
I’m going to close this in favour of https://github.com/orf/gping/issues/446, which is asking for the same thing.

feel free to re-open this if you feel it’s different
