### ISSUE TITLE
Cannot install from git

### ISSUE THREAD

**Issue by TragicWarrior** [orf/gping#46]
Using master (commit b2aecf2) I get the following error when trying to run setup.py:

sudo ./setup.py 
from: too many arguments
./setup.py: 4: ./setup.py: Syntax error: newline unexpected (expecting ")")

It's probably user error on the installation but snap and pip aren't an option for me.

Running Ubuntu 16.04.3 LTS x86-64
Python colorama 0.3.7 installed

**Comment by orf** [comment]
Hmm, that's weird. Can you put your setup.py here? Check out from git again, I cannot see any syntax errors at all and it runs fine on my machine.

Oh, perhaps try running `python setup.py install` instead of just `./setup.py`?

**Comment by TragicWarrior** [comment]
Okay.  So the latter worked.  I might suggest adding that to the readme.md.  However, I'm now getting a different error:

Traceback (most recent call last):
  File "/usr/local/bin/gping", line 9, in <module>
    load_entry_point('pinggraph==1.0', 'console_scripts', 'gping')()
  File "build/bdist.linux-x86_64/egg/gping/pinger.py", line 313, in run
  File "build/bdist.linux-x86_64/egg/gping/pinger.py", line 343, in _run
  File "build/bdist.linux-x86_64/egg/gping/pinger.py", line 181, in plot
  File "build/bdist.linux-x86_64/egg/gping/pinger.py", line 72, in vertical_line
StopIteration

**Comment by orf** [comment]
Thanks! I've fixed the first problem you ran into. The StopIteration one should also be fixed, can you try it with the latest git?

**Comment by orf** [comment]
I'm sure this is fixed. Let me know if not :+1:

**Comment by TragicWarrior** [comment]
All fixed now!
