### ISSUE TITLE
Does this package include any malware of any kind? 

### ISSUE THREAD

**Issue by marchershey** [orf/gping#463]
Hello, 

During my investigation of the [nope-ipc/peacenotwar protestware situation](https://en.wikipedia.org/wiki/Peacenotwar), I found that you were in support of [RIAEvangelist](https://github.com/RIAEvangelist) (the maintainer of [node-ipc](https://github.com/RIAEvangelist/node-ipc)) including malware ([peacenotwar](https://archive.ph/MesTy)) in his package. 

![Image of ORF's comment supporting RIAEvangelist actions of implementing malicious code](https://i.imgur.com/vsxtIBc.png)
([source](https://archive.ph/iLEkL#selection-139625.0-139812.0))

As this package (gping) is your package, do you have any plans in the near or far future to implement any type of malicious code?

Thanks for any info you can give me!

**Comment by orf** [comment]
Hey, thanks 😍 for the awesome 🚀 issue you opened ❤️

I’m so glad we’ve finally ⏰ got a professional like you investigating🕵️ that serious malware issue 🦠, and we all care 🤗 so much about your very unique ❄️ opinions on this relevant topic 🚨 

I’m really happy 😊 to have people like you 🫵 in this community 🏘️, it makes things so fun and enjoyable 🤩 

Now fuck off.
