### ISSUE TITLE
when resize windwos .before  last      min      max      avg   jtr      p95  s      t/o data lose

### ISSUE THREAD

**Issue by tqangxl** [orf/gping#464]
Windows gping-v1.17.3
![image](https://github.com/user-attachments/assets/0b04ca1b-bb18-4b4b-b9ab-f573e98271e0)

resize window 
![image](https://github.com/user-attachments/assets/fdcf67ac-99e7-4ece-a7d1-6244f475cb20)
resize window 
![image](https://github.com/user-attachments/assets/c9e4ca31-3f94-471c-b344-1d642c7167bb)

when resize windwos .before  last      min      max      avg   jtr      p95  s      t/o data lose

**Comment by orf** [comment]
Hey, it’s not clear what the specific issue is that you’re reporting. 

Can you elaborate more? I’m going to close this, but please re-open it when/if you can give more details.
