### ISSUE TITLE
Please provide text-based output

### ISSUE THREAD

**Issue by edwinjhlee** [orf/gping#483]
Hi, gping community ~

gping is awesome. 

I created [x-cmd](https://x-cmd.com) to deliver portable command tools, and we already include [gping](https://x-cmd.com/pkg/gping).

However, can gping provide text-based output like regular ping ? It would be nice if the output can be json/csv, or any easily parsed format.

The graphical output is awesome. However, sometimes, we just want the regular output like ping. The reason we don't use the traditional ping command is because it is unavailable in some minimalize environment ( like container ). In that situation, a relocatable ping ( which don't require sudo priviledge and affect the globlal dependency ) would save the day.

---

Also, can the community provide the mac arm build artifact ? 

Thank you for building such a wonderful tool ~

**Comment by t413** [comment]
+1 for adding some sort of --csv output for later analysis!

**Comment by orf** [comment]
Hey! I like the idea of adding a parsable ping output. I'm not sure if this should be a separate CLI though, or if we should bolt it into `gping`. Thoughts?

> The graphical output is awesome. However, sometimes, we just want the regular output like ping. The reason we don't use the traditional ping command is because it is unavailable in some minimalize environment ( like container ). In that situation, a relocatable ping ( which don't require sudo priviledge and affect the globlal dependency ) would save the day.

Can you elaborate? Right now, `gping` requires a traditional ping command to function.

**Comment by edwinjhlee** [comment]
Hi @orf 

I recently provide a visualization wrapper using shell/awk in x-cmd's `x ping` module, using the traditional ping command.  
This is the demo: https://cn.x-cmd.com/mod/ping

In environments where traditional ping is unavailable (e.g., containerized or minimal Linux environments), x-cmd dynamically downloads and utilizes `busybox ping`. 
The related source code is here: https://github.com/x-cmd/x-cmd/blob/be03713e530f1ec1fd1443c4d0e32ef2280e765c/mod/ping/lib/main#L36
    

However, two issues have surfaced with `busybox ping`:
    
1.  It requires `sudo` privileges, unlike GNU ping, which can send ICMP packets without elevated permissions.
2.  It returns no output on failure, disrupting x-cmd's current implementation.


We would like to introduce other ping implementation to address the problems mentioned above. And I think gping would be a pretty good candidate, if gping comes with an independant icmp solution and output csv or any other text-form stream results.


Thank you.

**Comment by orf** [comment]
> It requires sudo privileges, unlike GNU ping, which can send ICMP packets without elevated permissions.

this isn’t correct: both require elevated permissions (raw sockets can only be used by `root`). The difference in behaviour is down to setuid (https://en.m.wikipedia.org/wiki/Setuid): the pre-installed binaries have setuid set, whereas the one you download (rightly) does not.

This is the specific rationale behind the current behaviour of automating “ping” and scraping the output, however horrible that may be.

on Windows there is no such requirement, and gping utilises native calls to construct and send ping packets.

I’m not adverse to adding structured output, perhaps to a separate file, but bear in mind that:
1.  the entire point of this project is to provide a graphical interface to ping.
2. This won’t solve your actual problem

**Comment by edwinjhlee** [comment]
> > It requires sudo privileges, unlike GNU ping, which can send ICMP packets without elevated permissions.
> 
> this isn’t correct: both require elevated permissions (raw sockets can only be used by `root`). The difference in behaviour is down to setuid (https://en.m.wikipedia.org/wiki/Setuid): the pre-installed binaries have setuid set, whereas the one you download (rightly) does not.
> 
> This is the specific rationale behind the current behaviour of automating “ping” and scraping the output, however horrible that may be.
> 
> on Windows there is no such requirement, and gping utilises native calls to construct and send ping packets.
> 
> I’m not adverse to adding structured output, perhaps to a separate file, but bear in mind that:
> 
> 1. the entire point of this project is to provide a graphical interface to ping.
> 2. This won’t solve your actual problem

Yes, It did use the setuid method to address the privilege issue. Thanks for pointing that out.
    
Perhaps providing a portable GNU ping or using nping directly would likely be a better solution.

Thank you.
