### ISSUE TITLE
Would arm64 container images be a good addition?

### ISSUE THREAD

**Issue by dimaqq** [orf/gping#485]
docker run --rm -ti --network host ghcr.io/orf/gping:gping-v1.15.1 google.com
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
😢

**Comment by Identifier** [comment]
I also just ran into this when trying to run it (via docker) on a raspberry pi :(

**Comment by orf** [comment]
Thanks for this! I've added them in 03007482e486cddf332f848fd8139798a8db14b4 (and follow on commits).

They are building now and should be pushed soon.
