### ISSUE TITLE
Add axis label

### ISSUE THREAD

**Issue by G-Harmon** [orf/gping#54]
I've just discovered gping, and it's great. It would be even better if there were some simple axis label.

Also, is the current display linear or logarithmic?

**Comment by tylla** [comment]
Maybe the central window with the stats could be reorganized, to be split in four and shown on the left side on the proper place. This could be combined with #59. Something like this:
```
-------------------------------
|
110 #
▲   #
| # #
60  #
| # # #
▼#### ##### ##### ##### ##
20 ################################ ##### ##
|###########################################
-- Host: google.com (172.217.19.110) | Current: 20ms | Max: 110 ms | Avg: 60ms | Min: 20ms ------
```
