### ISSUE TITLE
Wrong ping numbers

### ISSUE THREAD

**Issue by mayankasthana** [orf/gping#72]
Installed via `cargo install gping` on ubuntu 18.04. `gping 0.1.4`

Ping response:

```
(base) _  ~ ping google.com
PING google.com (172.217.26.174) 56(84) bytes of data.
64 bytes from maa03s22-in-f174.1e100.net (172.217.26.174): icmp_seq=1 ttl=117 time=13.9 ms
64 bytes from maa03s22-in-f174.1e100.net (172.217.26.174): icmp_seq=2 ttl=117 time=13.7 ms
64 bytes from maa03s22-in-f174.1e100.net (172.217.26.174): icmp_seq=3 ttl=117 time=13.8 ms
64 bytes from maa03s22-in-f174.1e100.net (172.217.26.174): icmp_seq=4 ttl=117 time=13.7 ms
```

gping response:
![image](https://user-images.githubusercontent.com/2264215/99109687-345ff180-260f-11eb-92b4-d36c8a4d2819.png)

Sorry, my screenshot tool is only taking the top left portion of the screen. The p95 is 1.56ms, which for my connection is impossible.

The same issue occurs with all other hosts.

**Comment by archification** [comment]
I'm having the same problem. Was about to post my own issue when I saw this one.

**Comment by orf** [comment]
This was fixed in https://github.com/orf/pinger/commit/0f1b0e5a60229b17e85ddd91ab7f1885ba644730. I got the units wrong, so it was off by a factor of 10 😂.

Thanks for reporting!
