### ISSUE TITLE
Doesn't work under Windows 10 20H2

### ISSUE THREAD

**Issue by graphixillusion** [orf/gping#73]
Hi there. As the title says, i've just tried the last version under Windows 10 20H2 without success:

gping host = blank window with blinking cursor. Tried with standard cmd shell and the new Windows Terminal: same results.

**Comment by orf** [comment]
Would you mind running `ping google.com` and sending me the output? 5-10 lines would be ok.

**Comment by graphixillusion** [comment]
@orf tried version 0.1.6 and it works now. thank you.
