### ISSUE TITLE
Brew install not working on MacOS Big Sur

### ISSUE THREAD

**Issue by jdecool** [orf/gping#82]
I've tried to install `gping` on MacOS Big Sur (11.0), but it's not working with HomeBrew.

![image](https://user-images.githubusercontent.com/433926/99180682-9fe9b200-2728-11eb-9ec8-f91e6fdeb6e4.png)

I had to build it from sources.

**Comment by orf** [comment]
You [apparently need to update xcode](https://github.com/Homebrew/brew/issues/8797) and the dev tools. Run `xcode-select --install`

**Comment by jdecool** [comment]
Thanks @orf
