### ISSUE TITLE
feature request - rolling mean

### ISSUE THREAD

**Issue by jakob1379** [orf/gping#91]
Just found this nifty tool, thanks for it!

I would like to rocomment the feature of a shown mean, just for the time fram being shown, maybe with a standard deviation as well. This is to get a better estimate of what the average ping time is as well as the reliability of the connection, known from the standard deviation.

Again, thanks for the tool!
Jakob

**Comment by hbina** [comment]
I am working on a PR where you can dump this as a CSV. For the moment, you can use that to generate all this information with Excel or something. In general, we can generate all kinds of statistical information based on the CLI arg. I wonder if there are already statistical analysis crates out there.
