### ISSUE TITLE
Mac : brew install failed 

### ISSUE THREAD

**Issue by zcwfeng** [orf/gping#93]
~ brew install gping
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "gping".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

try brew tap also failed

**Comment by chaotianjiao** [comment]
I have the same issue in ubuntu20.04

**Comment by cisolarix** [comment]
Same issue encountered on macOS Big Sur 11.0.1

**Comment by lovetimi** [comment]
the same issue,  macOS 10.15.6

**Comment by orf** [comment]
Have you tried running `brew update` before running `brew install`?

**Comment by lovetimi** [comment]
> Have you tried running `brew update` before running `brew install`?

install success after running brew update  ^_^

**Comment by chaotianjiao** [comment]
> Have you tried running `brew update` before running `brew install`?

Thanks~,It works!~
