### ISSUE TITLE
Ctrl+C hangs for a second

### ISSUE THREAD

**Issue by samoylovfp** [orf/gping#95]
When hitting "Ctrl+C" the app doesn't quit immediately but waits for something for 0.5-2 seconds.
This hurts the user experience somewhat.

I don't experience similar problem with other command-line tools.

Some info about the system
```
Ubuntu 18.04.5 LTS
gnome-terminal
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
oh-my-zsh 3e6ee85a161
p10k d17c7278a5
```

Thanks for the awesome tool!

**Comment by hbina** [comment]
This is something that I have noticed as well. Still trying to figure out what actually happens but I am not that good at multithreaded things, maybe someone with more knowledge can shed a light.

**Comment by hbina** [comment]
Aha, this could be the culprit

https://github.com/orf/gping/blob/b83c763ed0aff2831527f8208d95252f44adbef9/src/main.rs#L170

There is still more opportunities to improve this, I think.

**Comment by orf** [comment]
I've reduced the duration between keyboard events to 100ms. This should help things a bit!
