### ISSUE TITLE
Build failed on Debian Buster (amd64)

### ISSUE THREAD

**Issue by CompuRoot** [orf/gping#97]
**$ cargo install gping**

```
error[E0658]: use of unstable library feature 'matches_macro'
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.12.0/src/backend/crossterm.rs:58:17
   |
58 |             if !matches!(last_pos, Some(p) if x == p.0 + 1 && y == p.1) {
   |                 ^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error[E0599]: no associated item named `MAX` found for type `usize` in the current scope
   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.12.0/src/buffer.rs:275:47
    |
275 |         self.set_stringn(x, y, string, usize::MAX, style);
    |                                               ^^^ associated item not found in `usize`
    |
help: you are looking for the module in `std`, not the primitive type
    |
275 |         self.set_stringn(x, y, string, std::usize::MAX, style);
    |                                        ^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0599, E0658.
For more information about an error, try `rustc --explain E0599`.
error: could not compile `tui`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `gping v0.1.7`, intermediate artifacts can be found at `/tmp/cargo-install5Kz6Qu`

Caused by:
  build failed
```

**Comment by hbina** [comment]
What version of `cargo` are you using? Consider installing `cargo` using `rustup` [here](curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh).

This feature was introduced way back in `1.42`.

**Comment by CompuRoot** [comment]
```
$ cargo --version
cargo 1.42.1
```

**Comment by hbina** [comment]
That's unfortunate,  especially since this is not without our control as its a dependency. I guess the author can revert to some older versions but that's not nice. I wish there is a transformation phase in Rust that de-sugars to some oldest possible version.

**Comment by orf** [comment]
I'm sorry, there isn't anything I can do here. It's unfortunate. I'll add a Docker image you could pull, or you can pre-build your binaries somewhere else before shipping them to production. I'm not sure if having a rust compiler on a "production" system is a great idea anyway.

**Comment by CompuRoot** [comment]
Thank you for taking a look on it. 
I think using docker image to be able to use ping like utility is overkill, but some1 may be find it useful.
As about rust compiler on "production" servers, - its fine, as far as it restricted to dedicated security groups, the same by the way applies to gcc, bash, gawk and anything else that can make network connections
